<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="7084" started-at="2018-02-23T08:52:54Z" finished-at="2018-02-23T08:53:01Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="7084" started-at="2018-02-23T08:52:54Z" finished-at="2018-02-23T08:53:01Z">
      <class name="Functional_Testing.User_TS">
        <test-method status="FAIL" signature="get()[pri:0, instance:Functional_Testing.User_TS@3a82f6ef]" name="get" duration-ms="7084" started-at="2018-02-23T14:22:54Z" finished-at="2018-02-23T14:23:01Z">
          <exception class="java.io.FileNotFoundException">
            <message>
              <![CDATA[\\Business_Talent\Testdata\BT.xlsx (The network path was not found)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.io.FileNotFoundException: \\Business_Talent\Testdata\BT.xlsx (The network path was not found)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at Common_Utilities.Datadriven.get(Datadriven.java:14)
	at Functional_Testing.Login_Design.login(Login_Design.java:28)
	at Functional_Testing.User_TS.get(User_TS.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.io.FileNotFoundException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- get -->
      </class> <!-- Functional_Testing.User_TS -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
